// <auto-generated />
using System;
using EduQuest.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduQuest.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260923222230_AddSourceExtractToQuizQuestion")]
    partial class AddSourceExtractToQuizQuestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduQuest.API.Models.Entities.Achievement", b =>
                {
                    b.Property<int>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementID"));

                    b.Property<string>("BadgeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("int");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ActivityLogID");

                    b.HasIndex("UserID");

                    b.ToTable("activityLogs");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Competition", b =>
                {
                    b.Property<int>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SponsorID")
                        .HasColumnType("int");

                    b.Property<string>("SponsorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetitionID");

                    b.HasIndex("SponsorID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.CompetitionLearner", b =>
                {
                    b.Property<int>("CompetitionLearnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionLearnerID"));

                    b.Property<int?>("CompetitionID")
                        .HasColumnType("int");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("CompetitionLearnerID");

                    b.HasIndex("CompetitionID");

                    b.HasIndex("LearnerID");

                    b.ToTable("CompetitionLearners");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.GradeSubject", b =>
                {
                    b.Property<int>("GradeSubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeSubjectID"));

                    b.Property<int>("GradeID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("GradeSubjectID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("GradeID", "SubjectID")
                        .IsUnique();

                    b.ToTable("GradeSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LeaderBoard", b =>
                {
                    b.Property<int>("LeaderboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaderboardID"));

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("LeaderboardID");

                    b.HasIndex("LearnerID");

                    b.ToTable("LeaderBoards");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Learner", b =>
                {
                    b.Property<int>("LearnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerID"));

                    b.Property<int>("GradeID")
                        .HasColumnType("int");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LearnerID");

                    b.HasIndex("GradeID");

                    b.HasIndex("SchoolID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerAchievement", b =>
                {
                    b.Property<int>("LearnerAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerAchievementID"));

                    b.Property<int>("AchievementID")
                        .HasColumnType("int");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.HasKey("LearnerAchievementID");

                    b.HasIndex("AchievementID");

                    b.HasIndex("LearnerID");

                    b.ToTable("LearnerAchievements");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerSubject", b =>
                {
                    b.Property<int>("LearnerSubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerSubjectID"));

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("LearnerSubjectID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("LearnerID", "SubjectID")
                        .IsUnique();

                    b.ToTable("learnerSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("DateSent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("LeanerID")
                        .HasColumnType("int");

                    b.Property<int?>("LearnerID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationID");

                    b.HasIndex("LearnerID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Prize", b =>
                {
                    b.Property<int>("PrizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrizeID"));

                    b.Property<int>("CompetitionID")
                        .HasColumnType("int");

                    b.Property<string>("PrizeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("PrizeID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceID"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceID");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceID = 1,
                            ProvinceName = "Eastern Cape"
                        },
                        new
                        {
                            ProvinceID = 2,
                            ProvinceName = "Free State"
                        },
                        new
                        {
                            ProvinceID = 3,
                            ProvinceName = "Gauteng"
                        },
                        new
                        {
                            ProvinceID = 4,
                            ProvinceName = "KwaZulu-Natal"
                        },
                        new
                        {
                            ProvinceID = 5,
                            ProvinceName = "Limpopo"
                        },
                        new
                        {
                            ProvinceID = 6,
                            ProvinceName = "Mpumalanga"
                        },
                        new
                        {
                            ProvinceID = 7,
                            ProvinceName = "Northern Cape"
                        },
                        new
                        {
                            ProvinceID = 8,
                            ProvinceName = "North West"
                        },
                        new
                        {
                            ProvinceID = 9,
                            ProvinceName = "Western Cape"
                        });
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.HasIndex("TopicID");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptID"));

                    b.Property<string>("DateTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("TimeTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizAttemptID");

                    b.HasIndex("LearnerID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttemptAnswer", b =>
                {
                    b.Property<int>("QuizAttemptAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptAnswerID"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("QuizAttemptID")
                        .HasColumnType("int");

                    b.Property<int>("QuizOptionID")
                        .HasColumnType("int");

                    b.Property<int?>("QuizQuestionID")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptAnswerID");

                    b.HasIndex("QuizAttemptID");

                    b.HasIndex("QuizOptionID");

                    b.HasIndex("QuizQuestionID");

                    b.ToTable("QuizAttemptAnswers");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttemptQuestion", b =>
                {
                    b.Property<int>("QuizAttemptQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptQuestionID"));

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuizAttemptID")
                        .HasColumnType("int");

                    b.Property<int>("QuizQuestionID")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptQuestionID");

                    b.HasIndex("QuizAttemptID");

                    b.HasIndex("QuizQuestionID");

                    b.ToTable("QuizAttemptQuestions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizOption", b =>
                {
                    b.Property<int>("QuizOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizOptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("QuizQuestionID")
                        .HasColumnType("int");

                    b.HasKey("QuizOptionID");

                    b.HasIndex("QuizQuestionID");

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizQuestion", b =>
                {
                    b.Property<int>("QuizQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizQuestionID"));

                    b.Property<bool>("ApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneratedByAI")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<string>("SourceExtract")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizQuestionID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Learner"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Sponsor"
                        });
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.School", b =>
                {
                    b.Property<int>("SchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolID"));

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolID = 1,
                            ProvinceID = 1,
                            SchoolName = "AM Zantsi Senior Secondary School"
                        },
                        new
                        {
                            SchoolID = 2,
                            ProvinceID = 1,
                            SchoolName = "Amabele Senior Secondary School"
                        },
                        new
                        {
                            SchoolID = 3,
                            ProvinceID = 1,
                            SchoolName = "Emdemi Senior Secondary School"
                        },
                        new
                        {
                            SchoolID = 4,
                            ProvinceID = 1,
                            SchoolName = "St Margaret Senior Secondary School"
                        },
                        new
                        {
                            SchoolID = 5,
                            ProvinceID = 1,
                            SchoolName = "St Matthews High School"
                        },
                        new
                        {
                            SchoolID = 6,
                            ProvinceID = 2,
                            SchoolName = "Sehlabeng Secondary School"
                        },
                        new
                        {
                            SchoolID = 7,
                            ProvinceID = 2,
                            SchoolName = "Sehunelo Secondary School"
                        },
                        new
                        {
                            SchoolID = 8,
                            ProvinceID = 2,
                            SchoolName = "Selelekelela Secondary School"
                        },
                        new
                        {
                            SchoolID = 9,
                            ProvinceID = 2,
                            SchoolName = "Seotlong A Secondary School"
                        },
                        new
                        {
                            SchoolID = 10,
                            ProvinceID = 2,
                            SchoolName = "Teto Secondary School"
                        },
                        new
                        {
                            SchoolID = 11,
                            ProvinceID = 3,
                            SchoolName = "Adam Masebe Secondary School"
                        },
                        new
                        {
                            SchoolID = 12,
                            ProvinceID = 3,
                            SchoolName = "Altmont Technical High School"
                        },
                        new
                        {
                            SchoolID = 13,
                            ProvinceID = 3,
                            SchoolName = "Asser Maloka Secondary School"
                        },
                        new
                        {
                            SchoolID = 14,
                            ProvinceID = 3,
                            SchoolName = "Bona Lesedi Secondary School"
                        },
                        new
                        {
                            SchoolID = 15,
                            ProvinceID = 3,
                            SchoolName = "Cosmo City Secondary School"
                        },
                        new
                        {
                            SchoolID = 16,
                            ProvinceID = 4,
                            SchoolName = "A.M. Moolla Secondary School"
                        },
                        new
                        {
                            SchoolID = 17,
                            ProvinceID = 4,
                            SchoolName = "Abaqulusi High School"
                        },
                        new
                        {
                            SchoolID = 18,
                            ProvinceID = 4,
                            SchoolName = "Amazondi Secondary School"
                        },
                        new
                        {
                            SchoolID = 19,
                            ProvinceID = 4,
                            SchoolName = "Bonga Secondary School"
                        },
                        new
                        {
                            SchoolID = 20,
                            ProvinceID = 4,
                            SchoolName = "Bukelakithi High School"
                        },
                        new
                        {
                            SchoolID = 21,
                            ProvinceID = 5,
                            SchoolName = "Abel Secondary School"
                        },
                        new
                        {
                            SchoolID = 22,
                            ProvinceID = 5,
                            SchoolName = "Abraham Serote Secondary School"
                        },
                        new
                        {
                            SchoolID = 23,
                            ProvinceID = 5,
                            SchoolName = "Adolf Mhinga Secondary School"
                        },
                        new
                        {
                            SchoolID = 24,
                            ProvinceID = 5,
                            SchoolName = "Alfred Ngwedzeni Secondary School"
                        },
                        new
                        {
                            SchoolID = 25,
                            ProvinceID = 5,
                            SchoolName = "Bambeni Secondary School"
                        },
                        new
                        {
                            SchoolID = 26,
                            ProvinceID = 6,
                            SchoolName = "Acorn-Oaks Comprehensive High School"
                        },
                        new
                        {
                            SchoolID = 27,
                            ProvinceID = 6,
                            SchoolName = "Alfred Matshine Commercial School"
                        },
                        new
                        {
                            SchoolID = 28,
                            ProvinceID = 6,
                            SchoolName = "Amadlelo Aluhlaza Secondary School"
                        },
                        new
                        {
                            SchoolID = 29,
                            ProvinceID = 6,
                            SchoolName = "Bee Maseko Secondary School"
                        },
                        new
                        {
                            SchoolID = 30,
                            ProvinceID = 6,
                            SchoolName = "Ben Matloshe High School"
                        },
                        new
                        {
                            SchoolID = 31,
                            ProvinceID = 7,
                            SchoolName = "!Xunkhwesa Combined School"
                        },
                        new
                        {
                            SchoolID = 32,
                            ProvinceID = 7,
                            SchoolName = "Ba Ga Lotlhare Intermediate School"
                        },
                        new
                        {
                            SchoolID = 33,
                            ProvinceID = 7,
                            SchoolName = "Bankhara Bodulong High School"
                        },
                        new
                        {
                            SchoolID = 34,
                            ProvinceID = 7,
                            SchoolName = "Banksdrif Secondary School"
                        },
                        new
                        {
                            SchoolID = 35,
                            ProvinceID = 7,
                            SchoolName = "Kimberley Boys' High School"
                        },
                        new
                        {
                            SchoolID = 36,
                            ProvinceID = 8,
                            SchoolName = "Areganeng Secondary School"
                        },
                        new
                        {
                            SchoolID = 37,
                            ProvinceID = 8,
                            SchoolName = "Badumedi Secondary School"
                        },
                        new
                        {
                            SchoolID = 38,
                            ProvinceID = 8,
                            SchoolName = "Nqunde Secondary School"
                        },
                        new
                        {
                            SchoolID = 39,
                            ProvinceID = 8,
                            SchoolName = "Ntshidi Secondary School"
                        },
                        new
                        {
                            SchoolID = 40,
                            ProvinceID = 8,
                            SchoolName = "Potchefstroom High School for Boys"
                        },
                        new
                        {
                            SchoolID = 41,
                            ProvinceID = 9,
                            SchoolName = "Dysselsdorp Sekondêr"
                        },
                        new
                        {
                            SchoolID = 42,
                            ProvinceID = 9,
                            SchoolName = "Fezekile Secondary School"
                        },
                        new
                        {
                            SchoolID = 43,
                            ProvinceID = 9,
                            SchoolName = "Fisantekraal High School"
                        },
                        new
                        {
                            SchoolID = 44,
                            ProvinceID = 9,
                            SchoolName = "Garden Route High School"
                        },
                        new
                        {
                            SchoolID = 45,
                            ProvinceID = 9,
                            SchoolName = "Woodlands Secondary School"
                        });
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Sponsor", b =>
                {
                    b.Property<int>("SponsorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponsorID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SponsorID");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.StudyMaterial", b =>
                {
                    b.Property<int>("StudyMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudyMaterialID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeSubjectID")
                        .HasColumnType("int");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopicID")
                        .HasColumnType("int");

                    b.HasKey("StudyMaterialID");

                    b.HasIndex("GradeSubjectID");

                    b.HasIndex("TopicID");

                    b.ToTable("StudyMaterials");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicID"));

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TopicID");

                    b.HasIndex("SubjectID", "GradeLevel", "TopicName")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.ActivityLog", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Competition", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Sponsor", "Sponsor")
                        .WithMany("Collections")
                        .HasForeignKey("SponsorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.CompetitionLearner", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Competition", "Competition")
                        .WithMany("CompetitionLearners")
                        .HasForeignKey("CompetitionID");

                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("CompetitionLearners")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.GradeSubject", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Grade", "Grade")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject", "Subject")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LeaderBoard", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("LeaderBoard")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Learner", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.School", "School")
                        .WithMany("Learners")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EduQuest.API.Models.Entities.Learner", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerAchievement", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Achievement", "Achievement")
                        .WithMany("LearnerAchievements")
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("LearnerAchievement")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerSubject", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("LearnerSubjects")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Notification", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("Notification")
                        .HasForeignKey("LearnerID");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Prize", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Competition", "Competition")
                        .WithMany("Prizes")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Quiz", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Topic", "Topic")
                        .WithMany("Quiz")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttempt", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("QuizAttempt")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttemptAnswer", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizAttemptID");

                    b.HasOne("EduQuest.API.Models.Entities.QuizOption", "QuizOption")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizQuestionID");

                    b.Navigation("QuizAttempt");

                    b.Navigation("QuizOption");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttemptQuestion", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizAttemptQuestions")
                        .HasForeignKey("QuizAttemptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizAttemptQuestions")
                        .HasForeignKey("QuizQuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuizAttempt");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizOption", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuizQuestionID");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizQuestion", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.School", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Province", "Province")
                        .WithMany("Schools")
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.StudyMaterial", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.GradeSubject", "GradeSubject")
                        .WithMany()
                        .HasForeignKey("GradeSubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GradeSubject");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Topic", b =>
                {
                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.User", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Achievement", b =>
                {
                    b.Navigation("LearnerAchievements");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Competition", b =>
                {
                    b.Navigation("CompetitionLearners");

                    b.Navigation("Prizes");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Grade", b =>
                {
                    b.Navigation("GradeSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Learner", b =>
                {
                    b.Navigation("CompetitionLearners");

                    b.Navigation("LeaderBoard");

                    b.Navigation("LearnerAchievement");

                    b.Navigation("LearnerSubjects");

                    b.Navigation("Notification");

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Province", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Quiz", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttempt", b =>
                {
                    b.Navigation("QuizAttemptAnswers");

                    b.Navigation("QuizAttemptQuestions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizOption", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizQuestion", b =>
                {
                    b.Navigation("QuizAttemptAnswers");

                    b.Navigation("QuizAttemptQuestions");

                    b.Navigation("QuizOptions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.School", b =>
                {
                    b.Navigation("Learners");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Sponsor", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Topic", b =>
                {
                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Subject", b =>
                {
                    b.Navigation("GradeSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
