// <auto-generated />
using System;
using EduQuest.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduQuest.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260904000827_Initial migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduQuest.API.Models.Entities.Achievement", b =>
                {
                    b.Property<int>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementID"));

                    b.Property<string>("BadgeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("int");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ActivityLogID");

                    b.HasIndex("UserID");

                    b.ToTable("activityLogs");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Competition", b =>
                {
                    b.Property<int>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SponsorID")
                        .HasColumnType("int");

                    b.Property<string>("SponsorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetitionID");

                    b.HasIndex("SponsorID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.CompetitionLearner", b =>
                {
                    b.Property<int>("CompetitionLearnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionLearnerID"));

                    b.Property<int?>("CompetitionID")
                        .HasColumnType("int");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("CompetitionLearnerID");

                    b.HasIndex("CompetitionID");

                    b.HasIndex("LearnerID");

                    b.ToTable("CompetitionLearners");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.GradeSubject", b =>
                {
                    b.Property<int>("GradeSubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeSubjectID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("GradeSubjectID");

                    b.HasIndex("GradeID");

                    b.HasIndex("SubjectID");

                    b.ToTable("GradeSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LeaderBoard", b =>
                {
                    b.Property<int>("LeaderboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaderboardID"));

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("LeaderboardID");

                    b.HasIndex("LearnerID");

                    b.ToTable("LeaderBoards");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Learner", b =>
                {
                    b.Property<int>("LearnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerID"));

                    b.Property<int>("GradeID")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LearnerID");

                    b.HasIndex("GradeID");

                    b.HasIndex("UserID");

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerAchievement", b =>
                {
                    b.Property<int>("LearnerAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerAchievementID"));

                    b.Property<int>("AchievementID")
                        .HasColumnType("int");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.HasKey("LearnerAchievementID");

                    b.HasIndex("AchievementID");

                    b.HasIndex("LearnerID");

                    b.ToTable("LearnerAchievements");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerSubject", b =>
                {
                    b.Property<int>("LearnerSubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerSubjectID"));

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("LearnerSubjectID");

                    b.HasIndex("LearnerID");

                    b.HasIndex("SubjectID");

                    b.ToTable("learnerSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("DateSent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("LeanerID")
                        .HasColumnType("int");

                    b.Property<int?>("LearnerID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationID");

                    b.HasIndex("LearnerID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Prize", b =>
                {
                    b.Property<int>("PrizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrizeID"));

                    b.Property<int>("CompetitionID")
                        .HasColumnType("int");

                    b.Property<string>("PrizeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("PrizeID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.HasIndex("TopicID");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptID"));

                    b.Property<string>("DateTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearnerID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("TimeTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizAttemptID");

                    b.HasIndex("LearnerID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttemptAnswer", b =>
                {
                    b.Property<int>("QuizAttemptAnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptAnswerID"));

                    b.Property<int>("AttemptID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("QuizAttemptID")
                        .HasColumnType("int");

                    b.Property<int>("QuizOptionID")
                        .HasColumnType("int");

                    b.Property<int?>("QuizQuestionID")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptAnswerID");

                    b.HasIndex("QuizAttemptID");

                    b.HasIndex("QuizOptionID");

                    b.HasIndex("QuizQuestionID");

                    b.ToTable("QuizAttemptAnswers");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizOption", b =>
                {
                    b.Property<int>("QuizOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizOptionID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("QuizQuestionID")
                        .HasColumnType("int");

                    b.HasKey("QuizOptionID");

                    b.HasIndex("QuizQuestionID");

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizQuestion", b =>
                {
                    b.Property<int>("QuizQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizQuestionID"));

                    b.Property<string>("ApprovedByAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedByAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("QuizQuestionID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Sponsor", b =>
                {
                    b.Property<int>("SponsorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponsorID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SponsorID");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.StudyMaterial", b =>
                {
                    b.Property<int>("StudyMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudyMaterialID"));

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeID")
                        .HasColumnType("int");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudyMaterialID");

                    b.HasIndex("GradeID");

                    b.HasIndex("SubjectID");

                    b.ToTable("StudyMaterials");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicID"));

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.ActivityLog", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Competition", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Sponsor", "Sponsor")
                        .WithMany("Collections")
                        .HasForeignKey("SponsorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.CompetitionLearner", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Competition", "Competition")
                        .WithMany("CompetitionLearners")
                        .HasForeignKey("CompetitionID");

                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("CompetitionLearners")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.GradeSubject", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Grade", "Grade")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Subject", "Subject")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LeaderBoard", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("LeaderBoard")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Learner", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerAchievement", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Achievement", "Achievement")
                        .WithMany("LearnerAchievements")
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("LearnerAchievement")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.LearnerSubject", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Notification", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("Notification")
                        .HasForeignKey("LearnerID");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Prize", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Competition", "Competition")
                        .WithMany("Prizes")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Quiz", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Topic", "Topic")
                        .WithMany("Quiz")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttempt", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Learner", "Learner")
                        .WithMany("QuizAttempt")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttemptAnswer", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizAttemptID");

                    b.HasOne("EduQuest.API.Models.Entities.QuizOption", "QuizOption")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuizQuestionID");

                    b.Navigation("QuizAttempt");

                    b.Navigation("QuizOption");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizOption", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuizQuestionID");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizQuestion", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.StudyMaterial", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduQuest.API.Models.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Topic", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.User", b =>
                {
                    b.HasOne("EduQuest.API.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Achievement", b =>
                {
                    b.Navigation("LearnerAchievements");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Competition", b =>
                {
                    b.Navigation("CompetitionLearners");

                    b.Navigation("Prizes");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Grade", b =>
                {
                    b.Navigation("GradeSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Learner", b =>
                {
                    b.Navigation("CompetitionLearners");

                    b.Navigation("LeaderBoard");

                    b.Navigation("LearnerAchievement");

                    b.Navigation("Notification");

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Quiz", b =>
                {
                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizAttempt", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizOption", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.QuizQuestion", b =>
                {
                    b.Navigation("QuizAttemptAnswers");

                    b.Navigation("QuizOptions");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Sponsor", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Subject", b =>
                {
                    b.Navigation("GradeSubjects");
                });

            modelBuilder.Entity("EduQuest.API.Models.Entities.Topic", b =>
                {
                    b.Navigation("Quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
